#!/usr/bin/env groovy

import groovy.io.*
import groovy.json.*

def parser = new JsonSlurper().setType(JsonParserType.INDEX_OVERLAY)

def main(args) {
  def srcDir = new File(args[0])
  def destDir = new File(args[1])
  srcDir.eachFileMatch(FileType.FILES, ~/.*\.json$/) { src ->
    def dest = new File(destDir, src.name.replaceFirst(/\.json$/, '.test-data.mts'))
    if (dest && src.lastModified() <= dest.lastModified()) {
      println "'$dest' is up to date."
      return
    }
    dest.write(generate(src), 'UTF-8')
    println "'$dest' is generated successfully."
  }
}

def generate(File src) {
  def dest = new StringBuilder('// This file is generated by scripts/gen-test-data-code.groovy\n\n')
  dest << 'export default ['
  parser.parse(src, 'UTF-8').each { ptn ->
    def binary = encode(ptn.text).collect { "0x${Integer.toHexString(it)}" }.join(', ')
    dest << """
      |  {
      |    name: "${ptn.name}",
      |    text: "${ptn.text}",
      |    binary: new Uint8Array([$binary]),
      |  },""".stripMargin()
  }
  dest << '\n];\n'
  dest.toString()
}

def encode(String text) {
  new ByteArrayOutputStream().with { bytes ->
    new ObjectOutputStream(bytes).withCloseable { it.writeUTF(text) }
    //  off | field          | value
    // -----|----------------|--------------------------------
    //    0 | magic          | STREAM_MAGIC
    //    2 | version        | STREAM_VERSION
    //    4 | tag            | TC_BLOCKDATA
    //    5 | size           | sizeof(length) + sizeof(bytes)
    //    6 | length         | sizeof(bytes)
    //    8 | bytes          | MUTF-8 encoded string
    def serial = bytes.toByteArray()
    assert serial[4] == ObjectStreamConstants.TC_BLOCKDATA
    serial[8..<serial.length].collect(Byte::toUnsignedInt)
  }
}
