// This file is generated by scripts/gen-testdatacode.groovy
const testdata = [
  {
    name: "The null character",
    text: "\u0000",
    binary: new Uint8Array([0xc0, 0x80]),
  },
  {
    name: "A character whose code point is between U+0001 and U+007F",
    text: "A",
    binary: new Uint8Array([0x41]),
  },
  {
    name: "A character whose code point is between U+0080 and U+07FF",
    text: "\u00C4",
    binary: new Uint8Array([0xc3, 0x84]),
  },
  {
    name: "A character whose code point is between U+0800 and U+FFFF",
    text: "\u3042",
    binary: new Uint8Array([0xe3, 0x81, 0x82]),
  },
  {
    name: "A character whose code point is above U+FFFF",
    text: "\uD83D\uDC22",
    binary: new Uint8Array([0xed, 0xa0, 0xbd, 0xed, 0xb0, 0xa2]),
  },
];
export default testdata;
