name: build
on:
  pull_request:
    paths:
      - '.editorconfig'
      - '.github/workflows/build.yaml'
      - 'biome.json'
      - 'mise.toml'
      - 'package.json'
      - 'packages/**'
      - 'pnpm-lock.json'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'
  push:
    branches:
      - master
    paths:
      - '.editorconfig'
      - '.github/workflows/build.yaml'
      - 'biome.json'
      - 'mise.toml'
      - 'package.json'
      - 'packages/**'
      - 'pnpm-lock.json'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: Install dependencies
        run: pnpm ci
      - name: Run build
        run: pnpm -r run build:ci
